#!/bin/bash
COUNTER_DIR="./counter_dir"
COUNTER_FILE="$COUNTER_DIR/serial_counter.txt"
LOCK_FILE="$COUNTER_DIR/serial_counter.lock"

mkdir -p "$COUNTER_DIR"
touch "$COUNTER_FILE" "$LOCK_FILE"
if [ ! -s "$COUNTER_FILE" ]; then
  echo 0 > "$COUNTER_FILE"
fi

(
  flock -x 200
  current=$(<"$COUNTER_FILE")
  next=$((current+1))
  printf "%05d\n" "$next"
  echo "$next" > "$COUNTER_FILE"
) 200>"$LOCK_FILE"
