#!/bin/bash
COUNTER_DIR="./counter_dir"
COUNTER_FILE="$COUNTER_DIR/serial_counter.txt"
LOCK_FILE="$COUNTER_DIR/serial_counter.lock"

mkdir -p "$COUNTER_DIR"
touch "$COUNTER_FILE" "$LOCK_FILE"
if [ ! -s "$COUNTER_FILE" ]; then
  echo 0 > "$COUNTER_FILE"
fi

exec 9>"$LOCK_FILE"
flock -x 9

current=$(cat "$COUNTER_FILE")
next=$((current + 1))

echo "$next" > "$COUNTER_FILE"
printf "%05d\n" "$next"

flock -u 9
exec 9>&-
